language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '9'
  - '8'

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

deploy:
  provider: script
  script: npm run deploy-storybook
  skip_cleanup: true
  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
